sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t omaroid/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true omaroid/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-react1"
    env: "DockerReact1-env"
    bucket_name: "elasticbeanstalk-eu-west-1-398692132493"
    bucket_path: "docker-react1" # by default the app name if no folder in s3
    on:
        branch: master
    access_key_id: $ACCESSKEYID
    secret_access_key: $ACCESSKEYSECRET
    
after_deploy:
    - echo "done deploying !"        