sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t omaroid/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true omaroid/docker-react npm run test

before_deploy:
    - unset access-key-id
    - unset secret-access-key

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-1-398692132493"
    bucket_path: "docker-react" # by default the app name if no folder in s3
    access_key_id: 
        secure: $access-key-id
    secret_access_key: 
        secure: "$secret-access-key"
    on:
        branch: master

after_deploy:
    - echo "done deploying !"        