version: '3'
services:
  react-app:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - /app/node_modules
      - .:/app
      #- /app/App.test.js # Approche 1
  react-test:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]